describe('Visit itera-qa', () => {
    beforeEach(() => {
        cy.visit('https://itera-qa.azurewebsites.net/')
    })

    it('Success to Visit Page', () => {
      //cy.visit('https://itera-qa.azurewebsites.net/')
      cy.get('h1').contains('Test Automation')
      .should('be.visible')
    })
})

Cypress.on('uncaught:exception', (err, runnable) => {
    return false
  })

describe('SignUp itera-qa', () => {
    it('Success to Sign Up Page', () => {
      cy.visit('https://itera-qa.azurewebsites.net/')
      cy.get('.form-inline > .navbar-nav > :nth-child(1) > .nav-link').click()
      cy.get('h2').should('contain.text', 'Add new user')
      cy.get(':nth-child(2) > .control-label').contains('First name')
      cy.get(':nth-child(3) > .control-label').contains('Surname')
      cy.get(':nth-child(4) > .control-label').contains('E-post')
      cy.get(':nth-child(5) > .control-label').contains('Mobile')
      cy.get(':nth-child(7) > .control-label').contains('Username')
      cy.get(':nth-child(8) > .control-label').contains('Password')
      cy.get(':nth-child(9) > .control-label').contains('Confirm password')
      .should('be.visible')
    })

    it('Success to Sign Up on Login Page', () => {
        cy.visit('https://itera-qa.azurewebsites.net/')
        cy.get('.form-inline > .navbar-nav > :nth-child(2) > .nav-link').click()
        //cy.visit('https://itera-qa.azurewebsites.net/Login')
        cy.get('.btn > a').click()
        cy.get('h2').should('contain.text', 'Add new user')
        .should('be.visible')
    })
})

describe('SignUp Success', () => {
    beforeEach(() => {
        cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
    })
    it.skip('Success Input Sign Up', () => {
    //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
    cy.get('[name="FirstName"]').type('Rezha')
    cy.get('[name="Surname"]').type('Sachrian')
    cy.get('[name="E_post"]').type('TEST')
    cy.get('[name="Mobile"]').type('08122222')
    cy.get('[name="Username"]').type('Rezhaesa')
    cy.get('[name="Password"]').type('123456')
    cy.get('[name="ConfirmPassword"]').type('123456')
    cy.get('#submit').click()
    cy.get('#label-success').should('contain.text', 'Registration Successful')
    .should('be.visible')
    })        
    it('Success After Input Sign Up Username Already Exist', () => {
    //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
    cy.get('[name="FirstName"]').type('Rezha')
    cy.get('[name="Surname"]').type('Esa')
    cy.get('[name="E_post"]').type('TEST')
    cy.get('[name="Mobile"]').type('08122222')
    cy.get('[name="Username"]').type('Rezha')
    cy.get('[name="Password"]').type('123456')
    cy.get('[name="ConfirmPassword"]').type('123456')
    cy.get('#submit').click()
    cy.get('.label-danger').should('contain.text', 'Username already exist')
    cy.get('[name="Username"]').clear()
    cy.get('[name="Username"]').type('ESA123')
    cy.get('#submit').click()
    cy.get('.label-success').should('contain.text', 'Registration Successful')
    .should('be.visible')
    })
})


describe('SignUp Failed', () => {
        beforeEach(() => {
            cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
})
    it('Error Input Empty Sign Up', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').clear()
        cy.get('[name="Surname"]').clear()
        cy.get('[name="E_post"]').clear()
        cy.get('[name="Mobile"]').clear()
        cy.get('[name="Username"]').clear()
        cy.get('[name="Password"]').clear()
        cy.get('[name="ConfirmPassword"]').clear()
        cy.get('#submit').click()
        cy.get('#FirstName-error').should('contain.text', 'Please enter first name')
        cy.get('#Surname-error').should('contain.text', 'Please enter surname')
        cy.get('#Username-error').should('contain.text', 'Please enter username')
        cy.get('#Password-error').should('contain.text', 'Please enter password')
    })

    it('Error Input Sign Up Empty First Name', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').clear()
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        cy.get('#FirstName-error').should('contain.text', 'Please enter first name')
        .should('be.visible')
    })

    it('Error Input Sign Up Empty Surname', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').clear()
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        cy.get('#Surname-error').should('contain.text', 'Please enter surname')
        .should('be.visible')
    })
    
    it('Error Input Sign Up Empty E-Post', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').clear()
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        .should('be.visible')
    })
    
    it('Error Input Sign Up Empty Mobile', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').clear()
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        .should('be.visible')
    })
    
    it('Error Input Sign Up Empty Username', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').clear()
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        cy.get('#Username-error').should('contain.text', 'Please enter username')
        .should('be.visible')
    })

    it('Error Input Sign Up Username Already Exist', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        cy.get('.label-danger').should('contain.text', 'Username already exist')
        .should('be.visible')
    })
    
    it('Error Input Sign Up Empty Password', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').clear()
        cy.get('[name="ConfirmPassword"]').type('123456')
        cy.get('#submit').click()
        cy.get('#ConfirmPassword-error').should('contain.text', "'Confirm password' and 'Password' do not match.")
        .should('be.visible')
    })
    
    it('Error Input Sign Up Empty Confirm Password', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').clear()
        cy.get('#submit').click()
        cy.get('#ConfirmPassword-error').should('contain.text', "'Confirm password' and 'Password' do not match.")
        .should('be.visible')
    })

    it('Error Input Sign Up Password Not Match', () => {
        //cy.visit('https://itera-qa.azurewebsites.net/UserRegister/NewUser')
        cy.get('[name="FirstName"]').type('Rezha')
        cy.get('[name="Surname"]').type('Esa')
        cy.get('[name="E_post"]').type('TEST')
        cy.get('[name="Mobile"]').type('08122222')
        cy.get('[name="Username"]').type('Rezha')
        cy.get('[name="Password"]').type('123456')
        cy.get('[name="ConfirmPassword"]').type('12345678')
        cy.get('#submit').click()
        cy.get('#ConfirmPassword-error').should('contain.text', "'Confirm password' and 'Password' do not match.")
        .should('be.visible')
    })
})